[tool.poetry]
name = "symphony-crypto-trading-libraries"
version = "0.1.0"
description = ""
authors = ["pinnace"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
